### ISSUE TITLE
Shulker Box Crafting is not detected

### ISSUE THREAD

**Issue by pizzanakin** [Zazsona/DecorHeads#11]
I have added mini blocks for all the shulker boxes to the heads.yml in the following manner:
```
mini-gray-shulker-box:
    name: Mini Gray Shulker Box
    texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOGM5MzYzNzhmN2IxYTcyYWM2NWI2YTI2YmY4NDZhZWNhMWVjZWYxZDlhMTVhNmJjYWJiODgyMmM4NTVmZWJhIn19fQ==
    sources: 
      default-drop-0:
        source-type: MINE_DROP
        blocks: 
          - GRAY_SHULKER_BOX
        drop-rate: 100
      default-drop-1:
        source-type: CRAFT_DROP
        recipe-results:
          - GRAY_SHULKER_BOX
        drop-rate: 100
```

The drop rates are at 100% just to make sure that the block is set up correctly. Breaking a colored shulker box works great and it gives a head drop all the time. However, crafting a colored shulker box does nothing.

Using the sources page of the wiki, I can confirm that the source is registered correctly. It says it should give the block 100% of the time when crafting the colored shulker box. Despite this info showing correctly, the plugin doesn't actually give the head when crafting.

I have added other heads as well today using the source type CRAFT_DROP in this same format and they all worked as they should. This leads me to assume there might be an issue with picking up the craft event for shulker boxes. But that's just my hypothesis.

Hopefully this issue can be fixed, so that the plugin works as advertised!
